references:
  docker_default: &docker_default
    docker:
      - image: circleci/node:10.16.1
  yarn_cache_key: &yarn_cache_key
    yarn-cache-{{ checksum "yarn.lock" }}
  restore_yarn: &restore_yarn
    restore_cache:
      key: *yarn_cache_key
  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - ./*
  attach_workspace: &attach_workspace
    attach_workspace:
      at: .

jobs:
  boostrap:
    <<: *docker_default
    steps:
      - checkout
      - *restore_yarn
      - run:
          name: yarn dependencies
          command: yarn
      - save_cache:
         key: *yarn_cache_key
         paths:
           - ~/.cache/yarn
      - *persist_to_workspace
  test:
    <<: *docker_default
    steps:
      - *attach_workspace
      - run:
          name: test
          command: |
            yarn run test
  # build:
  #   <<: *docker_default
  #   steps:
  #     - *attach_workspace
  #     - run: yarn run build

workflows:
  version: 2
  test:
    jobs:
      - boostrap
      - test:
          requires:
            - boostrap
