export const GET_REPO = 'repo/GET_REPO_DETAIL';
export const GET_REPO_SUCCESS = 'repo/GET_REPO_SUCCESS';
export const GET_REPO_STARGAZERS = 'repo/GET_REPO_STARGAZERS';
export const GET_REPO_STARGAZERS_SUCCESS = 'repo/GET_REPO_STARGAZERS_SUCCESS,';
export const GET_REPO_PULLS_ONE_PER_PAGE = 'repo/GET_REPO_PULLS_ONE_PER_PAGE';
export const GET_REPO_PULLS_COUNT_SUCCESS = 'repo/GET_REPO_PULLS_COUNT_SUCCESS';
export const CLEAR_REPO_STARGAZERS = 'repo/CLEAR_REPO_STARGAZERS';
